# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_pdf.mappers.ipynb.

# %% auto 0
__all__ = ['SegsMapper']

# %% ../../nbs/06_pdf.mappers.ipynb 2
from ..imports import *
from ..utils import *
from ..mapper import *
from .extract import *
from .df import *

# %% ../../nbs/06_pdf.mappers.ipynb 4
class SegsMapper(Mapper):
    """
    A custom mapper for PDF segmentation. It uses the `df_segs` function to extract the segments from the PDF.
    """

    def __init__(
        self,
        segs_model="HamzaFarhan/PDFSegs",
        udf=df_segs,
        udf_kwargs=dict(
            thresh=0.6,
            classes=["Work Experience", "Education", "Certifications", "Other"],
            other_class="Other",
        ),
        **kwargs,
    ):
        """
        Parameters
        ----------
        segs_model : str, optional
            The name of the model to use for segmentation, by default "HamzaFarhan/PDFSegs"
        udf : function, optional
            The function to use for extracting the segments, by default df_segs
        udf_kwargs : dict, optional
            The keyword arguments to pass to the `udf` function.
        """
        segs_model = load_segs_model(segs_model, device=default_device())
        udf_kwargs["segs_model"] = segs_model
        super().__init__(**locals_to_params(locals()))
