# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/01_app.ipynb.

# %% auto 0
__all__ = ['app', 'read_root', 'create', 'add', 'match_ems']

# %% ../../nbs/api/01_app.ipynb 2
from fastapi import FastAPI
from ..imports import *
from ..utils import *
from ..index.core import *
from .utils import *

# %% ../../nbs/api/01_app.ipynb 4
app = FastAPI(title="DreamAI API", version="0.0.2")


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.post("/index/create")
def create(index_data: IndexData):
    t1 = time()
    res = create_indexes(
        ems_folder=index_data.ems_folder,
        index_folder=index_data.index_folder,
        index_dim=768,
    )
    t2 = time()
    msg.good(f"Time taken: {t2-t1:.2f} seconds.", spaced=True)
    return res.get("result", res)

@app.post("/index/add")
def add(index_data: IndexData):
    t1 = time()
    res = create_indexes(
        ems_folder=index_data.ems_folder,
        index_folder=index_data.index_folder,
        index_dim=768,
    )
    t2 = time()
    msg.good(f"Time taken: {t2-t1:.2f} seconds.", spaced=True)
    return res.get("result", res)

@app.post("/index/matching")
def match_ems(match_data: MatchData):
    t1 = time()
    res = search_indexes(
        ems=match_data.ems,
        index_folder=match_data.index_folder,
        k=match_data.k,
    )
    t2 = time()
    msg.good(f"Time taken: {t2-t1:.2f} seconds.", spaced=True)
    return res.get("result", res)
